/// <reference path="./../../typings/index.d.ts" />;
import * as mongoose from 'mongoose';

export interface Ericsson_Eventinfo extends mongoose.Document {
  sys_created_by : String,
  sys_created_on : Date,
  sys_updated_by : String,
  sys_updated_on : Date,
  sys_perm : String,
  sys_org : String,
  u_agent : String,
  u_alertgroup : String,
  u_alertname : String,
  u_clearedby : String,
  u_element : String,
  u_elementstatus : String,
  u_emsname : String,
  u_eventid : String,
  u_firstoccurrence : String,
  u_faultowner : String,
  u_freqband : String,
  u_node : String,
  u_hostname : String,
  u_lastoccurrence : String,
  u_nodealias : String,
  u_severity : String,
  u_serverserial : String,
  u_sitepriority : String,
  u_summary : String,
  u_sourceservername : String,
  u_sourceserserver : String,
  u_ticketnumber : String,
  u_technology : String,
  u_ticketflag : String,
  u_cnsind : String,
  u_cnstype : String,
  u_backhaultype : String,
  u_backhaulaccesstype : String,
  u_ipa : String,
  u_drms : String,
  u_alertkey : String,
  u_identifier : String,
  u_threshold : String,
  u_region : String,
  u_oemmarketvendor : String,
  u_cascade : String,
  u_runbook_status : String,
  u_runbook_position : String,
  u_ticketstatus : String,
  u_prblmid : String,
  u_problemid : String,
};
