/// <reference path="./../../typings/index.d.ts" />;
import * as mongoose from 'mongoose';

export interface Metric_Min_Runbook extends mongoose.Document {
  idx : Number,
  id : String,
  src : String,
  ts : Number,
  ts_datetime : Date,
  tot_aborted : Number,
  cnt_aborted : Number,
  del_aborted : Number,
  tot_completed : Number,
  cnt_completed : Number,
  del_completed : Number,
  tot_gcondition : Number,
  cnt_gcondition : Number,
  del_gcondition : Number,
  tot_bcondition : Number,
  cnt_bcondition : Number,
  del_bcondition : Number,
  tot_ucondition : Number,
  cnt_ucondition : Number,
  del_ucondition : Number,
  tot_gseverity : Number,
  cnt_gseverity : Number,
  del_gseverity : Number,
  tot_cseverity : Number,
  cnt_cseverity : Number,
  del_cseverity : Number,
  tot_wseverity : Number,
  cnt_wseverity : Number,
  del_wseverity : Number,
  tot_sseverity : Number,
  cnt_sseverity : Number,
  del_sseverity : Number,
  tot_useverity : Number,
  cnt_useverity : Number,
  del_useverity : Number,
  tot_duration : Number,
  cnt_duration : Number,
  del_duration : Number,
};
