/// <reference path="./../../typings/index.d.ts" />;
import * as mongoose from 'mongoose';

export interface Rb_Task extends mongoose.Document {
  sys_created_by : String,
  sys_created_on : Date,
  sys_is_deleted : String,
  sys_mod_count : Number,
  sys_org : String,
  sys_updated_by : String,
  sys_updated_on : Date,
  assessor_auto_gen : Boolean,
  u_assessor_script : String,
  u_command : String,
  u_continuation : String,
  u_default_assess : String,
  u_default_severity : String,
  u_description : String,
  u_detail : String,
  encoded_command : String,
  u_expect_timeout : Number,
  u_general_id : String,
  u_inputfile : String,
  u_name : String,
  u_order : Number,
  u_parent_id : String,
  u_parent_type : String,
  parser_auto_gen : Boolean,
  u_parser_config : String,
  u_parser_script : String,
  u_parser_type : String,
  u_prompt_source : String,
  u_prompt_source_name : String,
  u_queue_name : String,
  u_queue_name_src : String,
  u_ref_runbook_params : String,
  u_repeat : Boolean,
  u_sample : String,
  u_summary : String,
  u_timeout : Number,
  u_ref_runbook_id : String,
};
