/// <reference path="./../../typings/index.d.ts" />;
import * as mongoose from 'mongoose';

export interface Resolve_Impex_Glide extends mongoose.Document {
  sys_created_by : String,
  sys_created_on : Date,
  sys_is_deleted : String,
  sys_mod_count : Number,
  sys_org : String,
  sys_updated_by : String,
  sys_updated_on : Date,
  u_actiontask_namespace : String,
  u_actiontask_name : String,
  u_cns_prefix : String,
  u_cns_name : String,
  u_description : String,
  u_module_name : String,
  u_name : String,
  u_options : String,
  u_property_namespace : String,
  u_property_name : String,
  u_query_names : String,
  u_query_values : String,
  u_scan : String,
  u_tablename : String,
  u_trigger_name : String,
  u_trigger_namespace : String,
  u_type : String,
  u_value : String,
  u_module : String,
};
